import type { Metadata, Viewport } from "next";
import "./styles/global.scss";
import SmoothScrolling from "./scroll/SmoothScrolling";
import StoreProvider from "../providers/StoreProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport= {
  width: "derive-width",
  height: "derive-height",
  initialScale: 1,
  maximumScale: 1
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <SmoothScrolling root noAnimation>
            {children}
          </SmoothScrolling>
        </StoreProvider>
      </body>
    </html>
  );
}
